# Generated by Django 2.2.6 on 2020-03-17 01:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200315_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 17, 1, 33, 7, 125297, tzinfo=utc)),
        ),
    ]
