# Generated by Django 2.2.6 on 2020-03-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200318_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-comments_posts__timestamp', '-comments_post__updated']},
        ),
    ]
